# Generated by Django 4.2.6 on 2023-10-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_authors', models.TextField(blank=True, null=True)),
                ('book_desc', models.TextField(blank=True, null=True)),
                ('book_edition', models.TextField(blank=True, null=True)),
                ('book_format', models.TextField(blank=True, null=True)),
                ('book_isbn', models.TextField(blank=True, null=True)),
                ('book_pages', models.TextField(blank=True, null=True)),
                ('book_rating', models.FloatField(blank=True, null=True)),
                ('book_rating_count', models.IntegerField(blank=True, null=True)),
                ('book_review_count', models.IntegerField(blank=True, null=True)),
                ('book_title', models.TextField(blank=True, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesan', models.TextField()),
                ('gambar', models.FileField(upload_to='')),
            ],
        ),
    ]
