# Generated by Django 4.2.6 on 2023-10-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forum', '0002_rename_pesan_forum_text_remove_forum_gambar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookform',
        ),
    ]
