# Generated by Django 4.2.6 on 2023-10-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forum', '0003_delete_bookform'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
