# Generated by Django 4.2.6 on 2023-10-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_alter_book_book_authors_alter_book_book_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=100)),
                ('books', models.ManyToManyField(related_name='categories', to='book.book')),
            ],
        ),
    ]
