# Generated by Django 4.2.6 on 2023-10-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default=1, max_length=255, verbose_name='author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(default=1, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='format',
            field=models.CharField(default=1, max_length=100, verbose_name='format'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.IntegerField(default=1, verbose_name='genre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.TextField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.IntegerField(default=1, verbose_name='isbn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pages',
            field=models.IntegerField(default=1, verbose_name='pages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=1, verbose_name='rating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
    ]
