# Generated by Django 4.2.6 on 2023-10-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
