# Generated by Django 4.2.6 on 2023-10-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_book_authors_alter_book_book_desc_and_more'),
        ('favorit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorit',
            name='book_authors',
        ),
        migrations.RemoveField(
            model_name='favorit',
            name='book_desc',
        ),
        migrations.RemoveField(
            model_name='favorit',
            name='book_edition',
        ),
        migrations.RemoveField(
            model_name='favorit',
            name='book_format',
        ),
        migrations.RemoveField(
            model_name='favorit',
            name='book_isbn',
        ),
        migrations.RemoveField(
            model_name='favorit',
            name='book_pages',
        ),
        migrations.RemoveField(
            model_name='favorit',
            name='book_rating',
        ),
        migrations.RemoveField(
            model_name='favorit',
            name='book_rating_count',
        ),
        migrations.RemoveField(
            model_name='favorit',
            name='book_review_count',
        ),
        migrations.RemoveField(
            model_name='favorit',
            name='book_title',
        ),
        migrations.RemoveField(
            model_name='favorit',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='favorit',
            name='image_url',
        ),
        migrations.AddField(
            model_name='favorit',
            name='amountOfBooks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorit',
            name='books',
            field=models.ManyToManyField(related_name='favorit', to='book.book'),
        ),
    ]
