# Generated by Django 4.2.6 on 2023-10-27 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorit', '0002_remove_favorit_book_authors_remove_favorit_book_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
