# Generated by Django 4.2.6 on 2023-10-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_authors', models.TextField()),
                ('book_desc', models.TextField()),
                ('book_edition', models.TextField()),
                ('book_format', models.TextField()),
                ('book_isbn', models.TextField()),
                ('book_pages', models.TextField()),
                ('book_rating', models.FloatField()),
                ('book_rating_count', models.IntegerField()),
                ('book_review_count', models.IntegerField()),
                ('book_title', models.TextField()),
                ('genres', models.TextField()),
                ('image_url', models.TextField()),
            ],
        ),
    ]
