# Generated by Django 4.2.7 on 2023-11-29 09:36

from django.db import migrations
from django.core.management import call_command


def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "book.json")


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_book_authors_alter_book_book_desc_and_more'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]   
