# Generated by Django 4.2.6 on 2023-10-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similar_books', models.TextField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
