# Generated by Django 4.2.6 on 2023-10-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='book_review_count',
        ),
        migrations.AddField(
            model_name='detail',
            name='book_review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
